CREATE TABLE IF NOT EXISTS categories(
categoryId INT PRIMARY KEY AUTO_INCREMENT,
categoryName VARCHAR(255),
categoryBudget INT,
cDate VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS users(
userId INT PRIMARY KEY AUTO_INCREMENT,
userName VARCHAR(255),
userDate VARCHAR(255)
);